---@class ColorschemeShuffler.Config
---@field blacklist table this is stored as { ['scheme'] = true } internally
---@field shuffle_events table
---@field notify boolean
--
---@class ColorschemeShuffler.UserConfig
---@field blacklist? string[]
---@field shuffle_events? table
---@field notify boolean?
